### ISSUE TITLE
DOSE not work with esx_realestateagentjob

### ISSUE THREAD

**Issue by x20i** [lossantosroleplay/esx_propertymotels#1]
when you open the esx_realestateagentjob you cannot sell a house or anything it just gets stocks

**Comment by chrisrogersukgb** [comment]
Thank you for letting me know, ill look into it as soon as possible.

**Comment by chrisrogersukgb** [comment]
Re Released as a seperated Resource
https://github.com/chrisrogersukgb/lsrp-motels

Please go back to your original ESX Propertys as it will interfer with the new lsrp-motels
